# Generated by Django 4.0.6 on 2022-07-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participants',
        ),
        migrations.DeleteModel(
            name='DashUser',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
