# Generated by Django 4.0.6 on 2022-07-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dash_ui', '0002_remove_meeting_participants_delete_dashuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datadump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=40, null=True)),
                ('counter', models.IntegerField(blank=True, db_column='Counter', null=True)),
            ],
            options={
                'db_table': 'datadump',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(blank=True, db_column='Username', max_length=50, null=True)),
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalTalktime',
            fields=[
                ('time_talked', models.IntegerField(blank=True, db_column='Time_talked', null=True)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dash_ui.users')),
            ],
            options={
                'db_table': 'total_talktime',
                'managed': False,
            },
        ),
    ]
